//<auto-generated />
namespace example.avro
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Microsoft.Hadoop.Avro;

    /// <summary>
    /// Used to serialize and deserialize Avro record example.avro.User.
    /// </summary>
    [DataContract(Namespace = "example.avro")]
    public partial class User
    {
        private const string JsonSchema = @"{""type"":""record"",""name"":""example.avro.User"",""fields"":[{""name"":""name"",""type"":""string""},{""name"":""favorite_number"",""type"":[""int"",""null""]},{""name"":""favorite_color"",""type"":[""string"",""null""]}]}";

        /// <summary>
        /// Gets the schema.
        /// </summary>
        public static string Schema
        {
            get
            {
                return JsonSchema;
            }
        }

        /// <summary>
        /// Gets or sets the name field.
        /// </summary>
        [DataMember]
        public string name { get; set; }

        /// <summary>
        /// Gets or sets the favorite_number field.
        /// </summary>
        [DataMember()]
        [NullableSchema]
        public Nullable<int> favorite_number { get; set; }

        /// <summary>
        /// Gets or sets the favorite_color field.
        /// </summary>
        [DataMember()]
        [NullableSchema]
        public string favorite_color { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="User"/> class.
        /// </summary>
        public User()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="User"/> class.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="favorite_number">The favorite_number.</param>
        /// <param name="favorite_color">The favorite_color.</param>
        public User(string name, Nullable<int> favorite_number, string favorite_color)
        {
            this.name = name;
            this.favorite_number = favorite_number;
            this.favorite_color = favorite_color;
        }
    }
}
